apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    app: rollout-nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout-nginx

  template:
    metadata:
      labels:
        app: rollout-nginx

    spec:
      containers:
        - name: rollout-nginx
          image: nginx:1.15.6
