apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-1
  labels:
    app: rollout-nginx
spec:
  type: LoadBalancer
  ports:
    - name: svc-nginx
      port: 80
      targetPort: 80
  selector:
    app: rollout-nginx
